# Generated by Django 5.0.8 on 2024-08-13 12:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('reading', models.FloatField()),
                ('unit', models.CharField(default='kWh', max_length=10)),
            ],
        ),
    ]
